from midiutil.MidiFile import MIDIFile
import xml.etree.ElementTree as ET
import json
import sys


def xml2mid(xmlfilename, midfilename):
    """
    Converts an xml file (as generated by the software) to a .mid file

    @param xmlfilename: full path to the xml file
    @param midfilename: full path to the mid output file
    @return: None
    """
    try:
        tree = ET.parse(xmlfilename)
    except FileNotFoundError:
        print("Cannot open", xmlfilename)
        return None

    root = tree.getroot()
    trials = root.find("trials")

    track = 0
    channel = 0
    time = 0
    tempo = 60  # In BPM -  use 60 so that time is just in seconds

    mymidi = MIDIFile(1)  # One track, defaults to format 1 (tempo track is created
    # automatically)
    mymidi.addTempo(track, time, tempo)

    for trial in trials:
        notes = trial.find("notes").text
        notesArray = json.loads(notes)
        startsongtime = notesArray[0][2]
        for m in notesArray:
            note = m[0]
            volume = m[1]
            starttime = m[2] - startsongtime
            endtime = m[3] - startsongtime
            duration = endtime - starttime
            mymidi.addNote(track, channel, note, starttime, duration, volume)

    with open(midfilename, "wb") as output_file:
        mymidi.writeFile(output_file)


if __name__ == "__main__":
    try:
        xmlfile: str = sys.argv[1]
    except IndexError:
        print("The first argument should be the xml filename")
        exit(1)

    try:
        midfile = sys.argv[2]
    except IndexError:
        midfile = xmlfile[0:-4] + ".mid"

    xml2mid(xmlfile, midfile)
